### PR TITLE
Reroute AutoML operator links to Google Translation links

### PR DESCRIPTION
**Pull request by e-galan**
Update deprecated AutoML operators with new links. Due to its future deprecation AutoML's URLs have been divided between Google Translation and Vertex AI services. This PR updates the operators that are going to be used only with Google Translation services. 

I opted to create a new module `airflow/providers/google/cloud/links/translate.py` and put the new links there instead of updating the existing AutoML links in `airflow/providers/google/cloud/links/automl.py` because:
- The links are leading to Google Translation urls anyway;
- Corresponding AutoML urls are no longer accessible and will be deprecated in the future;
- We were missing a module for the Google Translation links.

This PR is dependent on and should not be merged before https://github.com/apache/airflow/pull/38673 .

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by MaksYermak** [comment]
LGTM
@e-galan @VladaZakharova @moiseenkov @molcay  do we plan to remove unused links for AutoML service in a future? Or maybe we can remove unused links now?

**Comment by e-galan** [comment]
> LGTM @e-galan @VladaZakharova @moiseenkov @molcay do we plan to remove unused links for AutoML service in a future? Or maybe we can remove unused links now?

I don't know about the deprecation policy regarding the links. Can we just remove them, or should I add deprecation warnings?

**Comment by moiseenkov** [comment]
I'd follow our deprecation policy with all types of objects (not only hooks and operators), because customers' source code could import and use anything. That's why IMHO we should deprecate links if they are not needed, and delete them only after EOL.

**Comment by e-galan** [comment]
@MaksYermak @moiseenkov I added the deprecation warnings, please check.

**Pull request closed without merging**
